### ISSUE TITLE
Create Admin Dashbord

### ISSUE THREAD

**Issue by Chukwuemeka-Mba** [acumendigital/interns-logistics-app#1]
- Create the admin dashboard
- Sidebar
- Freights Page
- Freights detail

**Comment by SualaDev** [comment]
I would like to work on this

**Comment by chukwuemekasmba** [comment]
I changed the admin routes directory name to freights so it's consistent with the sidebar.

**Comment by Harithmetic1** [comment]
I implemented the Admin Dashboard Sidebar
