### ISSUE TITLE
Install Fonts and Dependencies for the Project & Create Directories

### ISSUE THREAD

**Issue by Chukwuemeka-Mba** [acumendigital/interns-logistics-app#11]

**Comment by Chukwuemeka-Mba** [comment]
I want to push this 🅿️

**Comment by chukwuemekasmba** [comment]
Dependencies:
- Node Sass.

**Comment by Harithmetic1** [comment]
I want to add a mixin.scss file, and link it in the nuxt modules

**Comment by Harithmetic1** [comment]
Make sure to run npm install when pulling from upstream.

**Comment by chukwuemekasmba** [comment]
I think we should keep this issue open till we finish the project
@Harithmetic1 @theyinda 

Would help us keep track of what everyone is installing.
If you're installing anything that will be used globally just come here and comment and tag the people involved. 

Namaste.

**Comment by chukwuemekasmba** [comment]
I installed the inter font so we can use for the admin pages. Would push in a few.
@Harithmetic1 
@SualaDev
